use proc_macro2::TokenStream;
use quote::*;

pub const FILE_HEADER_COMMENT: &str = r#"
// DO NOT EDIT THIS FILE
// This file was generated by https://github.com/tacogips/async-graphql-reverse
"#;

pub fn to_rust_docs_token(comment: &str) -> TokenStream {
    let comments: Vec<TokenStream> = comment
        .split("\n")
        .into_iter()
        .map(|each_comment_line| format!("///{}", each_comment_line).parse().unwrap())
        .collect();

    let result = comments
        .into_iter()
        .reduce(|acc, each| quote! {#acc #each });
    result.unwrap_or_else(|| quote! {})
}
