// DO NOT EDIT THIS FILE
// This file is generated by https://github.com/tacogips/async-graphql-reverse
use async_graphql::*;
#[derive(Enum, Copy, Clone, Debug, Eq, PartialEq)]
pub enum Status {
    Registered,
    EmailVerified,
}
