// DO NOT EDIT THIS FILE
// This file was generated by https://github.com/tacogips/async-graphql-reverse
use async_graphql::*;
///comment for object
///in multi line
#[derive(InputObject)]
pub struct CreateFriendMutationInput {
    pub user_id: ID,
    pub large_data: Upload,
}
#[derive(InputObject)]
pub struct RecursiveInput {
    pub id: Option<String>,
    pub input1: Option<Box<RecursiveInput>>,
    pub input2: Option<Vec<Option<Box<RecursiveInput>>>>,
}
