// DO NOT EDIT THIS FILE
// This file was generated by https://github.com/tacogips/async-graphql-reverse
use async_graphql::*;
#[derive(Debug, InputObject)]
pub struct CreateFriendMutationInput {
    pub user_id: ID,
}
#[derive(Debug, InputObject)]
pub struct RecursiveInput {
    pub id: Option<String>,
    pub input1: Option<Box<RecursiveInput>>,
    pub input2: Vec<Option<Box<RecursiveInput>>>,
}
