// DO NOT EDIT THIS FILE
// This file is generated by https://github.com/tacogips/async-graphql-reverse
use async_graphql::*;
#[derive(Debug, InputObject)]
pub struct CreateFriendMutationInput {
    pub user_id: ID,
}
