// DO NOT EDIT THIS FILE
// This file was generated by https://github.com/tacogips/async-graphql-reverse
use super::enums::Sex;
use super::enums::UserType;
use super::objects::Friend;
use super::objects::Me;
use async_graphql::*;
#[derive(Interface)]
#[graphql(
    field(name = "id", type = "ID"),
    field(name = "name", type = "String"),
    field(name = "sex", type = "Sex"),
    field(name = "ttype", type = "Option < UserType >")
)]
#[derive(Debug, Clone)]
pub enum User {
    Friend(Friend),
    Me(Me),
}
