// DO NOT EDIT THIS FILE
// This file was generated by https://github.com/tacogips/async-graphql-reverse
use super::enums::UserType;
use super::objects::Friend;
use super::objects::Me;
use async_graphql::*;
#[derive(Interface)]
#[graphql(
    field(name = "id", ty = "ID"),
    field(name = "user_type", ty = "Option<UserType>"),
    field(name = "is_active", ty = "bool")
)]
#[derive(Debug, Clone)]
pub enum User {
    Friend(Friend),
    Me(Me),
}
